import Link from "next/link";
import { DocsArticle, docLinkClass } from "@/components/docs/docs-article";
import { docsMetadata } from "@/components/docs/content";

export const metadata = docsMetadata("Track or resume a USDC transfer", "Find your CCTP transfer using its source transaction hash and understand attestation, claim and completed transfer states.", "/docs/recover");
export default function RecoveryPage() {
  return <DocsArticle title="Track or resume a transfer" category="Help" description="Your source transaction hash is the starting point. Check what has already completed before taking the next step." next={{ href: "/docs/how-it-works", label: "How it works" }} sections={[
    { id: "find-transfer", title: "Find your transfer", content: <><p>Open <Link href="/bridge" className={docLinkClass}>Find transfer</Link>, select the source network, and enter the transaction hash from your wallet or block explorer. Use the burn transaction, not a separate token approval.</p><p>This lookup checks supported CCTP v2 transfers by source transaction hash; it is not a protocol-wide explorer or a search of every transfer made by a wallet. Transfers from other interfaces may use different versions, routes, or recipient restrictions and are not guaranteed to be recoverable here.</p></> },
    { id: "check-status", title: "What does the status mean?", content: <ul><li><strong>No confirmed burn:</strong> check your wallet and source explorer for a pending, rejected, or failed transaction. An approval alone does not transfer your USDC.</li><li><strong>Awaiting attestation:</strong> the source burn has been found, but the signed Circle message is not available yet. Keep tracking the existing transfer.</li><li><strong>Ready to claim:</strong> connect the appropriate destination wallet and follow the claim prompt. Keep destination gas available.</li><li><strong>Mint submitted:</strong> check the destination transaction for confirmation before trying again.</li><li><strong>Complete:</strong> verify the destination balance on the correct network and the native USDC token.</li></ul> },
    { id: "history", title: "History and missing transfers", content: <><p><Link href="/history" className={docLinkClass}>Transfer history</Link> contains transfers saved in this browser. An empty history after changing browsers, devices, or clearing site data does not mean an on-chain transfer was lost. Use the source transaction hash to find it again.</p><p>If the lookup cannot find a recently submitted burn, check that it succeeded on the source explorer and allow time for indexing. Confirm the source network and full hash. Do not enter the approval hash or a destination mint hash.</p></> },
    { id: "expired-attestation", title: "Expired attestation or delayed claim", content: <><p>A Fast message can expire before it is claimed. The tracking flow can request a new attestation for the existing burn and wait for the updated message. This does not require sending the USDC again.</p><p>If the page stops checking or a claim fails, inspect the existing destination transaction before retrying. Check the connected wallet, destination network, and gas balance. For help with a persistent error, contact <a className={docLinkClass} href="https://t.me/twpks" target="_blank" rel="noopener noreferrer">CCTP.io support</a> with the source network, transaction hash, and error shown. Never share a seed phrase or private key.</p></> },
    { id: "questions", title: "Common questions", content: <><div><h3 className="font-medium text-foreground">Can I close the page?</h3><p>Save your source transaction hash first. You can use it to find a supported transfer again and continue any remaining claim steps.</p></div><div><h3 className="font-medium text-foreground">Why can’t I see USDC in my wallet?</h3><p>Check the destination network and native USDC token. A source burn confirmation is not proof of destination completion; inspect the destination mint status.</p></div><div><h3 className="font-medium text-foreground">Can I change the receiving address after sending?</h3><p>The destination recipient is encoded in the burn message. Review that address before confirming; the interface cannot rewrite a submitted transfer’s recipient.</p></div></> },
  ]} />;
}
