import Link from "next/link";
import { DocsArticle, docLinkClass } from "@/components/docs/docs-article";
import { docsMetadata } from "@/components/docs/content";

export const metadata = docsMetadata("How CCTP bridging works", "Learn how to move native USDC between networks with CCTP: burn, attestation, mint, and choosing Fast or Standard transfers.", "/docs/how-it-works");
export default function HowItWorksPage() {
  return <DocsArticle title="How it works" description="Move native USDC between networks with Circle CCTP. Here’s what happens from the moment you send to when your USDC arrives." next={{ href: "/docs/transfer-speed", label: "Fast & Standard transfers" }} sections={[
    { id: "choose-networks", title: "1. Choose your networks", content: <p>Select where your USDC is now and where you want it to arrive. Connect your wallet, enter an amount, and check the destination address. Use native USDC on the source network; a wrapped token with a similar name is not interchangeable. Keep native tokens available for gas on both networks.</p> },
    { id: "review-and-send", title: "2. Review and send", content: <p>Choose Fast or Standard and review the estimated time, fees, and amount you’ll receive. On EVM networks, an allowance approval may be required before the burn transaction. Review each wallet request and confirm the required transactions.</p> },
    { id: "receive-usdc", title: "3. Receive native USDC", content: <><p>CCTP burns USDC on the source network. Circle then provides an attestation: a signed message that allows USDC to be minted on the destination network. This transfers native USDC without creating a wrapped bridge token.</p><p>Follow the transfer screen and complete the destination claim when prompted. A confirmed source transaction does not, by itself, mean the destination mint has finished.</p></> },
    { id: "transfer-speed", title: "Fast or Standard?", content: <><p>Fast provides earlier attestation on eligible routes for a fee. Standard waits for the required source-chain confirmations. The bridge shows the available options and quote for your route; availability and timing can vary.</p><p><Link href="/docs/transfer-speed" className={docLinkClass}>Compare Fast and Standard by source chain</Link>, or see <Link href="/docs/fees" className={docLinkClass}>fees and transfer times</Link> for the difference between transfer fees and network gas.</p></> },
  ]}>
    <ol aria-label="CCTP transfer stages" className="flex flex-col gap-5 rounded-[10px] border border-border bg-card p-6 sm:flex-row sm:items-center sm:justify-between">{[{ label: "Source network", value: "Burn USDC" }, { label: "Circle", value: "Attestation" }, { label: "Destination network", value: "Mint USDC" }].map((step, index) => <li key={step.label} className="flex items-center gap-5"><div><p className="mb-2 text-xs uppercase tracking-wide text-muted-foreground">{step.label}</p><p className="text-[17px]">{step.value}</p></div>{index < 2 && <span className="hidden text-muted-foreground sm:block" aria-hidden>→</span>}</li>)}</ol>
  </DocsArticle>;
}
