import { ChainIcon } from "@/components/chain-icon";
import Link from "next/link";
import { DocsArticle, docLinkClass } from "./docs-article";
import type { RouteGuide } from "./content";

export function RouteGuideArticle({ route }: { route: RouteGuide }) {
  return <DocsArticle category="Route guides" title={`Bridge USDC from ${route.source} to ${route.destination}`} description={`Send native USDC to ${route.destination} using Circle CCTP. Follow the route, choose your transfer speed, and review the quote before you send.`} next={{ href: "/docs/recover", label: "Track or resume a transfer" }} sections={[
    { id: "before-you-start", title: "Before you start", content: <><p>You’ll need native USDC on {route.source} and {route.sourceGas} on {route.source} for source-network gas. Keep {route.destinationGas} on {route.destination} available for the destination claim. Gas balances belong to each network: a balance on the source does not pay for transactions on the destination.</p><p>{route.crossEcosystem ? `This route crosses EVM and Solana networks. Connect an EVM wallet and a Solana wallet, and check the destination address in the bridge. A Solana address is different from an EVM address.` : `Use an EVM wallet that supports both ${route.source} and ${route.destination}. Check the receiving address and switch to ${route.destination} when the claim screen requests it.`}</p>{route.source === "Base" && <p>Choose USDC issued natively on Base, not the older bridged USDbC token. This CCTP transfer uses burn and mint; it does not use a canonical rollup withdrawal.</p>}{route.destination === "Base" && <p>The destination asset is native USDC on Base, not USDbC. Make sure any app you plan to use accepts that asset.</p>}</> },
    { id: "how-to-bridge", title: `How to bridge ${route.source} → ${route.destination}`, content: <ol><li>Open the bridge and select <strong>{route.source}</strong> as the source and <strong>{route.destination}</strong> as the destination.</li><li>Enter your USDC amount and confirm the receiving wallet address.</li><li>Choose Fast where available for earlier attestation, or Standard. Review fees and the amount you’ll receive.</li><li>Confirm the required source transactions in your wallet. {route.source !== "Solana" && "You may need to approve USDC spending before the burn."}</li><li>Wait for attestation, then follow the destination claim steps. Confirm the completed mint before using your USDC.</li></ol> },
    { id: "time-and-fees", title: "Transfer time and fees", content: <><p>Timing depends on the source network, transfer type, attestation availability, and destination confirmation. Fast and Standard can have different confirmation requirements; use the live quote for the route rather than a fixed time estimate.</p><p>Review the Fast transfer fee where applicable, network gas, and the amount you’ll receive before confirming. <Link href="/docs/fees" className={docLinkClass}>Understand each fee component</Link>.</p></> },
    { id: "track-transfer", title: "Track your transfer", content: <p>Save the source transaction hash. If you leave before the transfer finishes, open <Link href="/bridge" className={docLinkClass}>Track transfer</Link>, select the source network, and import the hash to check its state. Follow the <Link href="/docs/recover" className={docLinkClass}>recovery guide</Link> for attestation and claim steps.</p> },
  ]}>
    <div className="space-y-6 rounded-[10px] border border-border bg-card p-6">
      <div className="flex flex-wrap items-center gap-4 text-xl">{[{ name: route.source, icon: route.sourceIcon }, { name: route.destination, icon: route.destinationIcon }].map((chain, index) => <span key={chain.name} className="flex items-center gap-3">{index === 1 && <span aria-hidden className="mr-1 text-muted-foreground">→</span>}<ChainIcon chainId={chain.icon === "solana" ? "Solana" : Number(chain.icon)} size={28} />{chain.name}</span>)}</div>
      <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><p className="text-sm leading-6 text-muted-foreground">Native USDC → Native USDC<br />Review timing and fees in the live quote.</p><Link href="/" className="shrink-0 rounded-lg bg-primary px-5 py-3 text-center text-sm font-semibold text-primary-foreground hover:bg-primary/90">Open bridge ↗</Link></div>
    </div>
  </DocsArticle>;
}
