import Link from "next/link";
import { DocsArticle, docLinkClass } from "@/components/docs/docs-article";
import { docsMetadata } from "@/components/docs/content";

export const metadata = docsMetadata("About CCTP.io and support", "Understand CCTP.io’s role, Circle CCTP infrastructure, wallet responsibilities, application fees, and transfer support.", "/docs/about");

export default function AboutPage() {
  return <DocsArticle category="Help" title="About CCTP.io" description="CCTP.io is an independent interface for moving native USDC through Circle’s Cross-Chain Transfer Protocol. It is not Circle’s official bridge application." next={{ href: "/docs/recover", label: "Transfer recovery" }} sections={[
    { id: "roles", title: "The interface and the protocol", content: <><p>CCTP.io helps you select a route, prepare wallet transactions, and follow a transfer through burn, attestation, and mint. Circle provides the CCTP protocol and attestation service used by those transfers.</p><p>Your wallet approves and signs the transactions. CCTP.io cannot rewrite the recipient of a confirmed burn or bypass the protocol’s requirements to mint USDC. Learn the sequence in <Link className={docLinkClass} href="/docs/how-it-works">How CCTP transfers work</Link>.</p></> },
    { id: "fees", title: "How the application is supported", content: <p>Fast transfers can include an application fee in addition to Circle’s protocol fee. Standard transfers incur a 100 USDC fee per cumulative 1 million USDC bridged per wallet. Review the current quote and Fee Details before signing; see <Link className={docLinkClass} href="/docs/fees">fees and transfer times</Link> for the differences between USDC charges and network gas.</p> },
    { id: "security", title: "What a transfer depends on", content: <><p>Transfers depend on the source and destination networks, CCTP contracts, Circle’s attestation service, and your wallet. A confirmed source burn still needs a valid attestation and a successful destination mint. Timing estimates are not completion guarantees.</p><p>Before signing, check both networks, the native USDC asset, the receiving address, and fees. Keep your source transaction hash so you can <Link className={docLinkClass} href="/bridge">find the transfer</Link> again. Never give a website or support contact your seed phrase or private key.</p></> },
    { id: "support", title: "Get help", content: <><p>Start with the <Link className={docLinkClass} href="/docs/recover">recovery guide</Link> for missing history, pending attestation, and claim problems. For application support, use <a className={docLinkClass} href="https://t.me/twpks" target="_blank" rel="noopener noreferrer">CCTP.io’s Telegram support contact</a>. Include the source network, transaction hash, and the error shown so the transfer can be identified.</p><p>The application’s public updates are available on <a className={docLinkClass} href="https://x.com/lewifree" target="_blank" rel="noopener noreferrer">X</a>. These are CCTP.io contacts, separate from Circle’s support channels.</p></> },
  ]} />;
}
